# -*- coding: utf-8 -*-
"""571-Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XyuEg5z0Ny5bn4PrWbTHUGXPx_gYXwqb
"""

from bs4 import BeautifulSoup
from pprint import pprint

filenames = [
    'thread1.html',
    'thread2.html',
    'thread3.html',
    'thread4.html',
    'thread5.html',
    'thread6.html',
    'thread7.html',
    'thread8.html',
    'thread9.html',
    'thread10.html'
]

json_list = list()

for filename in filenames:

  with open(filename, 'r') as file:
    html = file.read()

  soup = BeautifulSoup(html, 'html.parser')


  authors = [a.get_text() for a in soup.find_all('a', class_=["_3I7vNNNM", "E7NPJ3WK", "comment-detail-author-name"])]

  neighborhoods_post = [a.get_text() for a in soup.find_all('a', class_="post-byline-redesign", limit=1)]
  neighborhoods_comments = [a.get_text() for a in soup.find_all('a', class_="_2CC8ezgv")]
  neighborhoods = neighborhoods_post + neighborhoods_comments

  comments = [span.get_text() for span in soup.find_all('span', class_="Linkify")]

  reactions = []

  parent_divs = soup.find_all('div', class_=["post-action-count-container", "comment-thank-container"])

  for div in parent_divs:
    child_div = div.find('div', class_=["_2b1vgpTX", "xKjQlGKr", "_3n6Fnd22"])
    value = child_div.get_text() if child_div else '0'
    reactions.append(value)

  posts = [
    {"author": author, "neighborhood": neighborhood, "comment": comment, "reactions": reaction}
    for author, neighborhood, comment, reaction in zip(authors, neighborhoods, comments, reactions)
  ]

  json_list.extend(posts)

len(json_list)

import json

with open('nextdoor_posts.json', 'w') as output_file:
    json.dump(json_list, output_file, indent=2)